#this automation switches all lights of when i leave the house.
- alias: 'lichten_uit_bij_vertrek'
  hide_entity: true
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights

#When away, if the backdoor opens. message paterPhone.
- alias: 'alarm_openen_achterdeur'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.backdoor
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.ios_pater100
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de achterdeur'

#one light only can be on at one time upstairs
- alias: 'Als lampen aan in werkkamer'
  hide_entity: true
  trigger:
    platform: state
    entity_id: light.werkkamer_group
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.Bedroom_en_bathroom_off
- alias: 'Als lampen aan in slaapkamer'
  hide_entity: true
  trigger:
    platform: state
    entity_id: light.slaapkamer_group
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.office_en_bathroom_off
- alias: 'als lampen aan in badkamer'
  hide_entity: true
  trigger:
    platform: state
    entity_id: light.badkamer_group
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.Bedroom_en_office_off

#Bayesian Sensor accuratie test
- alias: 'Pressence_detected_Home'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.patrick_presence
    to: 'on'
  action:
    service: notify.ios_pater100
    data:
      title: 'Patrick is Thuis!'
      message: 'De sensor is geschakeld naar thuis'
- alias: 'Pressence_detected_Away'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.patrick_presence
    to: 'off'
  action:
    service: notify.ios_pater100
    data:
      title: 'Patrick is niet meer thuis!'
      message: 'De sensor is geschakeld naar Afwezig'

#Turning Versterker on when tv turns on
- alias: 'Turn Homecinema Set on when TV is on'
  hide_entity: true
  initial_state: true
  trigger:
    - entity_id: media_player.samsung_tv_remote
      platform: state
      to: 'on'
  action:
    data:
      entity_id: script.versterker_aan
    service: script.turn_on

- alias: 'turn Homecinema Set off when TV is off'
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: media_player.samsung_tv_remote
      platform: state
      to: 'off'
  action:
    data:
      entity_id: script.versterker_aan
    service: script.turn_on

- alias: 'tv on after sunset, turn on ambiance scene'
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: media_player.samsung_tv_remote
      platform: state
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    data:
      entity_id: scene.ambiance
    service: scene.turn_on

#lights can't turn on when not at home
- alias: "lights can't turn on when nobady is home"
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: group.all_lights
      platform: state
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.patrick_presence
    state: 'off'
  action:
    data:
      entity_id: scene.alle_lampen_uit
    service: scene.turn_on