#   _                      
#  /_\__      ____ _ _   _ 
# //_\\ \ /\ / / _` | | | |
#/  _  \ V  V / (_| | |_| |
#\_/ \_/\_/\_/ \__,_|\__, |
#                    |___/ 
- alias: 'lichten_uit_bij_vertrek'
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: 'screen on when home'
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: home
  action:
    service: switch.turn_on
    entity_id: switch.wallscreen

- alias: 'screen off when home'
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: not_home
    for: '00:08:00'
  action:
    service: switch.turn_off
    entity_id: switch.wallscreen
  
#     __      _   _  __ _           _   _                 
#  /\ \ \___ | |_(_)/ _(_) ___ __ _| |_(_) ___  _ __  ___ 
# /  \/ / _ \| __| | |_| |/ __/ _` | __| |/ _ \| '_ \/ __|
#/ /\  / (_) | |_| |  _| | (_| (_| | |_| | (_) | | | \__ \
#\_\ \/ \___/ \__|_|_| |_|\___\__,_|\__|_|\___/|_| |_|___/
#                                                         
- alias: 'alarm_openen_achterdeur'
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'away'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de achterdeur'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0

- alias: 'alarm_openen_Voordeur'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de voordeur'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0

- alias: 'alarm_openen_schuurdeur'
  trigger:
    platform: state
    entity_id: binary_sensor.schuur_deur
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de schuurdeur'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0

- alias: 'alarm_openen_schuurpoort'
  trigger:
    platform: state
    entity_id: binary_sensor.schuur_poort
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de schuurpoort'
- alias: 'notification when fire alarm goes off Kitchen'
  trigger:
    platform: state
    entity_id: binary_sensor.fire_54
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: "Brand"
      message: 'Het brand alarm gaat af! Keuken!'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0

- alias: 'notification when fire alarm goes off Replicator Room'
  trigger:
    platform: state
    entity_id: binary_sensor.rookmelder_replicator_room
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: "Brand"
      message: 'Het brand alarm gaat af! Replicator room!'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0

- alias: 'notification when fire alarm goes off slaapkamer'
  trigger:
    platform: state
    entity_id: binary_sensor.rookmelder_slaapkamer
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: "Brand"
      message: 'Het brand alarm gaat af! Slaapkamer!'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0

- alias: 'Announce Coming home'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  action:
    service: tts.cloud_say
    entity_id: media_player.slaapkamer
    data:
      message: 'Initializing, Welcome Home, I am Starting up Paterhome'
#   __ _       _     _                   _                 
#  / /(_) __ _| |__ | |_   ___ _   _ ___| |_ ___ _ __ ___  
# / / | |/ _` | '_ \| __| / __| | | / __| __/ _ \ '_ ` _ \ 
#/ /__| | (_| | | | | |_  \__ \ |_| \__ \ ||  __/ | | | | |
#\____/_|\__, |_| |_|\__| |___/\__, |___/\__\___|_| |_| |_|
#        |___/                 |___/                       

#light System in Shed
- alias: "if shed door opens turn shed lights on"
  initial_state: true
  trigger:
    - entity_id: binary_sensor.schuur_deur
      platform: state
      to: 'on'
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_on

- alias: door closed? turn off lights after 5 minutes
  initial_state: true
  trigger: 
    - entity_id: binary_sensor.schuur_deur
      platform: state
      to: 'off'
      for:
        minutes: 2
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_off

- alias: "if shed backdoor opens turn on shed lights"
  initial_state: true
  trigger:
    - entity_id: binary_sensor.schuur_poort
      platform: state
      to: 'on'
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_on

- alias: Poort closed? turn off lights after 5 minutes
  initial_state: true
  trigger:
    - entity_id: binary_sensor.schuur_poort
      platform: state
      to: 'off'
      for:
        minutes: 2
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_off

- alias: if front door opens turn on lights, but only when its dark
  initial_state: true
  trigger:
    entity_id: binary_sensor.front_door
    platform: state
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    data:
      entity_id: light.gang_group
    service: light.turn_on

- alias: if front door closes turn off lights
  initial_state: true
  trigger:
    entity_id: binary_sensor.front_door
    platform: state
    to: 'off'
    for:
      minutes: 1
  action:
    data:
      entity_id: light.gang_group
    service: light.turn_off

- alias: if motion on stairs is detected turn off all light on upper floor
  initial_state: true
  trigger:
    entity_id: binary_sensor.stairs
    platform: state
    to: "on"
  action:
    data:
      entity_id: light.boven_group
    service: light.turn_off

- alias: if door opens in the cellar
  initial_state: true
  trigger:
    entity_id: binary_sensor.kelder
    platform: state
    to: "on"
  action:
    data:
      entity_id: light.kelder_2
    service: light.turn_on

- alias: if door opens in the cellar
  initial_state: true
  trigger:
    entity_id: binary_sensor.kelder
    platform: state
    to: "off"
  action:
    data:
      entity_id: light.kelder_2
    service: light.turn_off

- alias: if replicator room on is pressed turn on studymode
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 00:17:88:01:04:f7:38:fa
      event: 1002
  action:
    data:
      entity_id: light.werkkamer_group
    service: light.turn_ons

- alias: if replicator room off is pressed turn off studymode
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 00:17:88:01:04:f7:38:fa
      event: 4002
  action:
    data:
      entity_id: light.werkkamer_group
    service: light.turn_off
      

- alias: if iPaterMac Turns on turn on workligt
  trigger:
    entity_id: binary_sensor.imac_van_patrick_active
    platform: state
    to: "on"
  action:
    data:
      entity_id: light.downstairs_workarea
    service: light.turn_on
      

- alias: if iPaterMac Turns off turn off workligt
  trigger:
    entity_id: binary_sensor.imac_van_patrick_active
    platform: state
    to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.study_mode
      state: "off" 
  action:
    data:
      entity_id: light.downstairs_workarea
    service: light.turn_off
      
#   ___ _                                             _                 _   _             
#  / _ \ | __ _ _   _  __ _ _ __ ___  _   _ _ __   __| |  ___  ___  ___| |_(_) ___  _ __  
# / /_)/ |/ _` | | | |/ _` | '__/ _ \| | | | '_ \ / _` | / __|/ _ \/ __| __| |/ _ \| '_ \ 
#/ ___/| | (_| | |_| | (_| | | | (_) | |_| | | | | (_| | \__ \  __/ (__| |_| | (_) | | | |
#\/    |_|\__,_|\__, |\__, |_|  \___/ \__,_|_| |_|\__,_| |___/\___|\___|\__|_|\___/|_| |_|
#               |___/ |___/                                                               
- alias: 'Pressence_detected_Home'
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: 'home'
  action:
    service: notify.mobile_app_paterphone
    data:
      title: 'Patrick is Thuis!'
      message: 'De sensor is geschakeld naar thuis'
- alias: 'Pressence_detected_Away'
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: not_home
  action:
    service: notify.mobile_app_paterphone
    data:
      title: 'Patrick is niet meer thuis!'
      message: 'De sensor is geschakeld naar Afwezig'

#              _ _   _                    _ _       
#  /\/\  _   _| | |_(_)_ __ ___   ___  __| (_) __ _ 
# /    \| | | | | __| | '_ ` _ \ / _ \/ _` | |/ _` |
#/ /\/\ \ |_| | | |_| | | | | | |  __/ (_| | | (_| |
#\/    \/\__,_|_|\__|_|_| |_| |_|\___|\__,_|_|\__,_|                                                   
- alias: 'Turn Homecinema Set on when TV is on'
  initial_state: true
  trigger:
    - entity_id: media_player.pater_panel
      platform: state
      to: 'on'
  action:     
    data:
      entity_id: remote.livingroom_2
      command:
        - PowerToggle
      device: 46809977
    service: remote.send_command

- alias: 'turn Homecinema Set off when TV is off'
  initial_state: true
  trigger:
    - entity_id: media_player.pater_panel
      platform: state
      to: 'off'
  action:     
    data:
      entity_id: remote.livingroom_2
      command:
        - PowerToggle
      device: 46809977
    service: remote.send_command

- alias: 'tv on after sunset, turn on ambiance scene'
  initial_state: true
  trigger:
    - entity_id: media_player.pater_panel
      platform: state
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    data:
      entity_id: scene.ambiance
    service: scene.turn_on

- alias: pop-up when doorbel dings
  initial_state: true
  trigger:
    platform: event
    event_data:
      entity_id: sensor.ring_front_door_last_ding
    event_type: state_changed
  action:
    data:
      entity_id: script.popup_front_door
    service: script.turn_on

- alias: pop-up when doorbel dings
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.schuur_poort
    to: "on"
  action:
    data:
      entity_id: script.popup_back_door
    service: script.turn_on
#                          _ _         
# ___  ___  ___ _   _ _ __(_) |_ _   _ 
#/ __|/ _ \/ __| | | | '__| | __| | | |
#\__ \  __/ (__| |_| | |  | | |_| |_| |
#|___/\___|\___|\__,_|_|  |_|\__|\__, |
#                                |___/ 
- alias: 'if frontdoor opens at night, turn lights on in bedroom'
  initial_state: true
  trigger:
    - entity_id: binary_sensor.front_door
      platform: state
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.patrick_smits
      state: 'home'
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    data:
      entity_id: scene.slaapkamer_lichten_100
    service: scene.turn_on
- alias: 'if backdoor opens at night, turn lights on in bedroom'
  initial_state: true
  trigger:
    - entity_id: person.patrick_smits
      platform: state
      to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.patrick_smits
      state: 'home'
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    data:
      entity_id: scene.slaapkamer_lichten_100
    service: scene.turn_on

#  __  __                  _               ____             _   _            
# |  \/  | ___  _ __ _ __ (_)_ __   __ _  |  _ \ ___  _   _| |_(_)_ __   ___ 
# | |\/| |/ _ \| '__| '_ \| | '_ \ / _` | | |_) / _ \| | | | __| | '_ \ / _ \
# | |  | | (_) | |  | | | | | | | | (_| | |  _ < (_) | |_| | |_| | | | |  __/
# |_|  |_|\___/|_|  |_| |_|_|_| |_|\__, | |_| \_\___/ \__,_|\__|_|_| |_|\___|
#                                  |___/                                     

- alias: "turn off sleep modus"
  initial_state: true
  trigger:
    platform: time
    at: '05:00:00'
  action:
    data:
      entity_id: input_boolean.sleep_mode
    service: input_boolean.turn_off

- alias: "wake-up start of the routine"
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.wakeup_enabled
      state: 'on'
    - condition: or
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: input_boolean.wakeup_weekend
          state: 'on'
  action:
    data:
      entity_id: script.morning
    service: script.turn_on

#  _   _ _       _     _     ____             _   _            
# | \ | (_) __ _| |__ | |_  |  _ \ ___  _   _| |_(_)_ __   ___ 
# |  \| | |/ _` | '_ \| __| | |_) / _ \| | | | __| | '_ \ / _ \
# | |\  | | (_| | | | | |_  |  _ < (_) | |_| | |_| | | | |  __/
# |_| \_|_|\__, |_| |_|\__| |_| \_\___/ \__,_|\__|_|_| |_|\___|
#          |___/   
- alias: when night mode is on, set house to sleep mode
  initial_state: true
  trigger: 
    platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
  condition:
    condition: time
    after: '21:00:00'
    before: '05:00:00'
  action:
    data:
      entity_id: script.nightmode
    service: script.turn_on

- alias: Button for bedtime routine
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_masterswitch
      event: 4002
  condition:
    condition: time
    after: '21:00:00'
    before: '05:00:00'
  action:
    data:
      entity_id: script.button_night
    service: script.turn_on
#   ____ _                  _             
#  / ___| | ___  __ _ _ __ (_)_ __   __ _ 
# | |   | |/ _ \/ _` | '_ \| | '_ \ / _` |
# | |___| |  __/ (_| | | | | | | | | (_| |
#  \____|_|\___|\__,_|_| |_|_|_| |_|\__, |
#                                   |___/

- alias: start the clean up session.
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
    for: "01:30:00"
  action:
    data:
      entity_id: vacuum.pater_zuiger_2
    service: vacuum.start

- alias: Charge kitchen ipad when empty
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.ipadje_battery_level_2
    below: 11
  action:
    data:
      entity_id: switch.ipad_charger
    service: switch.turn_on

- alias: stop Charge kitchen ipad when full
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.ipadje_battery_level_2
    above: 99
  action:
    data:
      entity_id: switch.ipad_charger
    service: switch.turn_off