#   _                      
#  /_\__      ____ _ _   _ 
# //_\\ \ /\ / / _` | | | |
#/  _  \ V  V / (_| | |_| |
#\_/ \_/\_/\_/ \__,_|\__, |
#                    |___/ 
- alias: 'lichten_uit_bij_vertrek'
  hide_entity: true
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: "lights can't turn on when nobady is home"
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: group.all_lights
      platform: state
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.patrick_presence
    state: 'off'
  action:
    data:
      entity_id: scene.alle_lampen_uit
    service: scene.turn_on

#     __      _   _  __ _           _   _                 
#  /\ \ \___ | |_(_)/ _(_) ___ __ _| |_(_) ___  _ __  ___ 
# /  \/ / _ \| __| | |_| |/ __/ _` | __| |/ _ \| '_ \/ __|
#/ /\  / (_) | |_| |  _| | (_| (_| | |_| | (_) | | | \__ \
#\_\ \/ \___/ \__|_|_| |_|\___\__,_|\__|_|\___/|_| |_|___/
                                                         
- alias: 'alarm_openen_achterdeur'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.backdoor
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.ios_pater100
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de achterdeur'
- alias: 'alarm_openen_Voordeur'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.frontdoor
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.ios_pater100
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de voordeur'
- alias: 'alarm_openen_schuurdeur'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.schuurdeur
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.ios_pater100
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de schuurdeur'
- alias: 'alarm_openen_schuurpoort'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.schuurpoort
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.ios_pater100
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de schuurpoort'

#   __ _       _     _                   _                 
#  / /(_) __ _| |__ | |_   ___ _   _ ___| |_ ___ _ __ ___  
# / / | |/ _` | '_ \| __| / __| | | / __| __/ _ \ '_ ` _ \ 
#/ /__| | (_| | | | | |_  \__ \ |_| \__ \ ||  __/ | | | | |
#\____/_|\__, |_| |_|\__| |___/\__, |___/\__\___|_| |_| |_|
#        |___/                 |___/                       
- alias: 'Als lampen aan in werkkamer'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.replicator_motion_sensor
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.Bedroom_en_bathroom_off
- alias: 'Als lampen aan in slaapkamer'
  hide_entity: true
  trigger:
    platform: state
    entity_id: light.slaapkamer_group
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.office_en_bathroom_off
- alias: 'als lampen aan in badkamer'
  hide_entity: true
  trigger:
    platform: state
    entity_id: light.badkamer_group
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.Bedroom_en_office_off

#light System in Shed
- alias: "if shed door opens turn shed lights on"
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: binary_sensor.schuurdeur
      platform: state
      to: 'on'
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_on

- alias: door closed? turn off lights after 5 minutes
  initial_state: true
  hide_entity: true
  trigger: 
    - entity_id: binary_sensor.schuurdeur
      platform: state
      to: 'off'
      for:
        minutes: 2
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_off

- alias: "if shed backdoor opens turn on shed lights"
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: binary_sensor.schuurpoort
      platform: state
      to: 'on'
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_on

- alias: Poort closed? turn off lights after 5 minutes
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: binary_sensor.schuurpoort
      platform: state
      to: 'off'
      for:
        minutes: 2
  action:
    data:
      entity_id: switch.schuur
    service: switch.turn_off

#   ___ _                                             _                 _   _             
#  / _ \ | __ _ _   _  __ _ _ __ ___  _   _ _ __   __| |  ___  ___  ___| |_(_) ___  _ __  
# / /_)/ |/ _` | | | |/ _` | '__/ _ \| | | | '_ \ / _` | / __|/ _ \/ __| __| |/ _ \| '_ \ 
#/ ___/| | (_| | |_| | (_| | | | (_) | |_| | | | | (_| | \__ \  __/ (__| |_| | (_) | | | |
#\/    |_|\__,_|\__, |\__, |_|  \___/ \__,_|_| |_|\__,_| |___/\___|\___|\__|_|\___/|_| |_|
#               |___/ |___/                                                               
- alias: 'Pressence_detected_Home'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.patrick_presence
    to: 'on'
  action:
    service: notify.ios_pater100
    data:
      title: 'Patrick is Thuis!'
      message: 'De sensor is geschakeld naar thuis'
- alias: 'Pressence_detected_Away'
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.patrick_presence
    to: 'off'
  action:
    service: notify.ios_pater100
    data:
      title: 'Patrick is niet meer thuis!'
      message: 'De sensor is geschakeld naar Afwezig'

#              _ _   _                    _ _       
#  /\/\  _   _| | |_(_)_ __ ___   ___  __| (_) __ _ 
# /    \| | | | | __| | '_ ` _ \ / _ \/ _` | |/ _` |
#/ /\/\ \ |_| | | |_| | | | | | |  __/ (_| | | (_| |
#\/    \/\__,_|_|\__|_|_| |_| |_|\___|\__,_|_|\__,_|                                                   
- alias: 'Turn Homecinema Set on when TV is on'
  hide_entity: true
  initial_state: true
  trigger:
    - entity_id: media_player.samsung_tv_remote
      platform: state
      to: 'on'
  action:
    data:
      entity_id: script.versterker_aan
    service: script.turn_on

- alias: 'turn Homecinema Set off when TV is off'
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: media_player.samsung_tv_remote
      platform: state
      to: 'off'
  action:
    data:
      entity_id: script.versterker_aan
    service: script.turn_on

- alias: 'tv on after sunset, turn on ambiance scene'
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: media_player.samsung_tv_remote
      platform: state
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    data:
      entity_id: scene.ambiance
    service: scene.turn_on

#                          _ _         
# ___  ___  ___ _   _ _ __(_) |_ _   _ 
#/ __|/ _ \/ __| | | | '__| | __| | | |
#\__ \  __/ (__| |_| | |  | | |_| |_| |
#|___/\___|\___|\__,_|_|  |_|\__|\__, |
#                                |___/ 
- alias: 'if frontdoor opens at night, turn lights on in bedroom'
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: binary_sensor.frontdoor
      platform: state
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.patrick_presence
      state: 'on'
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    data:
      entity_id: scene.slaapkamer_lichten_100
    service: scene.turn_on
- alias: 'if backdoor opens at night, turn lights on in bedroom'
  initial_state: true
  hide_entity: true
  trigger:
    - entity_id: binary_sensor.backdoor
      platform: state
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.patrick_presence
      state: 'on'
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    data:
      entity_id: scene.slaapkamer_lichten_100
    service: scene.turn_on

