#this automation switches all lights of when i leave the house.
- alias: 'lichten_uit_bij_vertrek'
  trigger:
    platform: state
    entity_id: person.patrick_smits
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights

#When away, if the backdoor opens. message paterPhone.
- alias: 'alarm_openen_achterdeur'
  trigger:
    platform: state
    entity_id: binary_sensor.backdoor
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: person.patrick_smits
      state: 'not_home'
  action:
    service: notify.ios_pater100
    data:
      title: 'Indringer!'
      message: 'Iemand komt binnen via de achterdeur'

#one light only can be on at one time upstairs
- alias: 'Als lampen aan in werkkamer'
  trigger:
    platform: state
    entity_id: light.werkkamer_group
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: 'sunset'
    after_offset: '-01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.Bedroom_en_bathroom_off
- alias: 'Als lampen aan in slaapkamer'
  trigger:
    platform: state
    entity_id: light.slaapkamer_group
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: 'sunset'
    after_offset: '-01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.office_en_bathroom_off
- alias: 'als lampen aan in badkamer'
  trigger:
    platform: state
    entity_id: light.badkamer_group
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: 'sunset'
    after_offset: '-01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.Bedroom_en_office_off

#Bayesian Sensor accuratie test
- alias: 'Pressence_detected_Home'
  trigger:
    platform: state
    entity_id: binary_sensor.patrick_presence
    to: 'on'
  action:
    service: notify.ios_pater100
    data:
      title: 'Patrick is Thuis!'
      message: 'De sensor is geschakeld naar thuis'
- alias: 'Pressence_detected_Away'
  trigger:
    platform: state
    entity_id: binary_sensor.patrick_presence
    to: 'off'
  action:
    service: notify.ios_pater100
    data:
      title: 'Patrick is niet meer thuis!'
      message: 'De sensor is geschakeld naar Afwezig'