homeassistant:
  # Name of the location where Home Assistant is running
  name: PaterHome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Network information


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
#themes
frontend:
  themes: !include themes.yaml

panel_iframe:
  valetudo:
    title: Pater-zuiger
    icon: mdi:robot-vacuum-variant
    url: !secret ip_pater_zuiger_iframe

#input Booleans
input_boolean:
  sleep_mode:
    name: Sleepmode
    icon: mdi:sleep
  wakeup_enabled:
    name: "wake-up lights"
    initial: on
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "wake-up Weekend"
    initial: on
    icon: mdi:brightness-4

input_datetime:
  wakeup_time:
    name: "Weekday Routine"
    has_time: true
    has_date: false
    initial: "06:15"

# Homekit entitie injectie
homekit:
  filter:
    include_domains:
      - climate
      - script
      - switch
      - input_booleans
      - light
      - switch

calendar:
  - platform: caldav
    username: !secret caldav_username
    password: !secret caldav_password
    url: https://caldav.icloud.com

vacuum:
  - platform: xiaomi_miio
    host: !secret pater_zuiger
    token: !secret Pater_zuiger_token
    name: Pater-Zuiger

recorder:
  # Ignore some entities that generate lots of data and aren't useful
  exclude:
    entities:
      - sensor.xiaomi_map

#camera
stream:
camera:
  - platform: foscam
    ip: !secret foscam_ip_voor
    username: !secret foscam_username_voor
    password: !secret foscam_password_voor
    name: Foscam Voor
  - platform: foscam
    ip: !secret foscam_ip_achter
    username: !secret foscam_username_achter
    password: !secret foscam_password_achter
    name: Foscam Achter

#het weer
weather:
  - platform: buienradar
    name: 'Uden'
    # Forceer 'Meetstation Uden
    latitude: !secret weerstation_latitude
    longitude: !secret weerstation_longitude
    forecast: true

# Human pressence detection system (beta)
device_tracker:
  - platform: unifi_direct
    host: !secret device_tracker_unifi_host
    username: !secret device_tracker_user
    password: !secret device_tracker_password
    new_device_defaults:
      track_new_devices: true
  #custom component for detecting Paterphone
  - platform: iphonedetect
    consider_home: 60
    hosts:
      iPhone_Paterphone: !secret Paterphone_ip
  # ping naat paterphone voor pressence detection 
  - platform: ping
    hosts:
      hostone: !secret Ping_host_Paterphone

#configuratie Owntrack
owntracks:

#Dezonz Logger
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

#thermostaat
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#ring
ring:
  username: !secret ring_username 
  password: !secret ring_password

#Harmony hubb
remote:
  - platform: harmony
    name: livingroom
    host: !secret remote_host

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  #raam sensoren
  - platform: mqtt
    name: "Voor-links"
    state_topic: "Voorraam-links"
  - platform: mqtt
    name: "voor-rechts"
    state_topic: "Voorraam-rechts"
  #glances (Sensor from host)
  - platform: glances
    host: !secret glances_host
    version: 3
    resources:
      - 'memory_use_percent'
      - 'cpu_use_percent'
      - 'memory_free'
      - 'memory_use'
      - 'disk_use'
      - 'disk_free'
  #platform rest API
  - platform: rest
    name: CPU-temprature
    resource: !secret CPU_temp_sensor_adres
    value_template: '{{ value_json[3]["value"] }}'
    unit_of_measurement: "°C"
  #pi-hole
  - platform: pi_hole
  #ring Sensor
  - platform: ring
  #Version Checker
  - platform: version
    name: version_availeble
    source: hassio
    image: qemux86-64
  - platform: version
    name: version_current
  - platform: time_date
    display_options:
      - 'time'
  - platform: dsmr_reader
  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data"
    name: xiaomi_map
    value_template: 'OK'
  - platform: authenticated
  - platform: launch_library
  - platform: jumbo
    username: !secret jumbo_username
    password: !secret jumbo_password
    type: "both"

binary_sensor:
  # Bayesian Sensor
  - platform: bayesian
    prior: 0.5
    name: 'Patrick presence'
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.iphone_paterphone'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.pater100_owntrack'
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'paterhome'
      - entity_id: 'device_tracker.paterphone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
  #binary Octoprint

#ios intergratie
ios:
apple_tv:
  - host: !secret applt_tv_ip
    login_id: !secret apple_tv_login
    name: apple TV Livingroom
    start_off: true
    credentials: !secret apple_tv_credentials

#mqtt broker
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

#SabNZBD
sabnzbd:
  api_key: !secret sabnzbd_api
  host: !secret sabnzbd_host

#media player apparaten
media_player:
  - platform: samsungtv
    host: !secret tv_ip

proxmoxve:
  host: !secret proxmox_ip
  verify_ssl: false
  username: !secret proxmox_username
  password: !secret proxmox_password
  realm: pve
  nodes:
  - node: Proxmox
    vms:
      - 100
      - 108
      - 109
    containers:
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret tts_url
    language: 'nl'

#HACS
hacs:
  token: !secret Git_hub_token

#iBeacon zones (in need for change)
zone:
  - name: 'paterhome'
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100

#checking for updates
updater:

#BrowserMOD
browser_mod:
  prefix: "browser_"
  devices:
    067973d0-c081114f:
      name: Wall-display


# UI
lovelace:
  mode: yaml

#sun
sun:

system_health:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include lights.yaml
switch: !include switch.yaml
scene: !include scene.yaml