homeassistant:
  # Name of the location where Home Assistant is running
  #name: PaterHome
  # Location required to calculate the time the sun rises and sets
  #latitude: !secret latitude
  #longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  #elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  #unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  #Internal and External Urls
  #external_url: !secret base_url
  #internal_url: !secret internal_url
  

# Network information


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#themes
frontend:
  themes: !include_dir_merge_named themes

#input Booleans
input_boolean:
  sleep_mode:
    name: Sleepmode
    icon: mdi:sleep
  wakeup_enabled:
    name: "wake-up lights"
    initial: off
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "wake-up Weekend"
    initial: off
    icon: mdi:brightness-4

input_datetime:
  wakeup_time:
    name: "Weekday Routine"
    has_time: true
    has_date: false
    initial: "06:15"

# Homekit entitie injectie
homekit:
  filter:
    include_domains:
      - climate
      - script
      - switch
      - input_booleans
      - light
      - switch
    include_entities:
      - sensor.bedroom_temperature
      - sensor.temperature_60
      - sensor.temperature_57
      - camera.paternet_foscam_huis_achter
      - camera.paternet_foscam_voor
    exclude_entity_globs:
      - light.browser


calendar:
  - platform: caldav
    username: !secret caldav_username
    password: !secret caldav_password
    url: https://caldav.icloud.com

vacuum:
  - platform: xiaomi_miio
    host: !secret pater_zuiger
    token: !secret Pater_zuiger_token
    name: Pater-Zuiger

recorder:
  # Ignore some entities that generate lots of data and aren't useful
  exclude:
    entities:
      - sensor.xiaomi_map

#camera
#stream:
#camera:
# - platform: foscam
#    ip: !secret foscam_ip_voor
#    username: !secret foscam_username_voor
#    password: !secret foscam_password_voor
#    name: Foscam Voor
#  - platform: foscam
#    ip: !secret foscam_ip_achter
#    username: !secret foscam_username_achter
#    password: !secret foscam_password_achter
#    name: Foscam Achter

# Human pressence detection system (beta)
  #custom component for detecting Paterphone
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    hosts:
      iPhone_Paterphone: !secret Paterphone_ip
  # ping naat paterphone voor pressence detection 
  - platform: ping
    hosts:
      hostone: !secret Ping_host_Paterphone

#configuratie Owntrack
owntracks:

#Dezonz Logger
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

#Harmony hubb
remote:
  - platform: harmony
    name: livingroom
    host: !secret remote_host

# Sensors
sensor:
  #Version Checker
  - platform: version
    name: version_availeble
    source: hassio
    image: qemux86-64
  - platform: version
    name: version_current
  - platform: time_date
    display_options:
      - 'time'
  #- platform: dsmr_reader
  - platform: authenticated
  - platform: launch_library
  # - platform: unifigateway
  #   host: !secret unifi_host
  #   username: !secret unifi_username
  #   password: !secret unifi_password
    version: UDMP-unifiOS
    port: 443
    monitored_conditions:
      - www
      - wlan
      - wan
      - alerts
      - firmware
      - lan

binary_sensor:
  # Bayesian Sensor
  - platform: bayesian
    prior: 0.5
    name: 'Patrick presence'
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.iphone_paterphone'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.pater100_owntrack'
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'paterhome'
      - entity_id: 'device_tracker.paterphone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'

#ios intergratie
ios:
apple_tv:
  - host: !secret applt_tv_ip
    login_id: !secret apple_tv_login
    name: apple TV Livingroom
    start_off: true
    credentials: !secret apple_tv_credentials

#mqtt broker
#mqtt:
  #broker: !secret mqtt_broker
  #username: !secret mqtt_user
  #password: !secret mqtt_password

proxmoxve:
  host: !secret proxmox_ip
  verify_ssl: false
  username: !secret proxmox_username
  password: !secret proxmox_password
  realm: pve
  nodes:
  - node: Proxmox
    vms:
      - 100
      - 104
      - 108
      - 109
    containers:
      - 101
      - 102
      - 103
      - 105
      - 106
      - 107

#WebOS
webostv:
  host: !secret Paterpannel-ip
  name: Pater-panel

# Text to speech
tts:

#iBeacon zones (in need for change)
# zone:
#   - name: 'paterhome'
#     latitude: !secret latitude
#     longitude: !secret longitude
#     radius: 100

#BrowserMOD
browser_mod:
  prefix: "browser_"
  devices:
    067973d0-c081114f:
      name: Wall-display


# UI
lovelace:
  mode: yaml
  resources: !include resources.yaml
  dashboards:
    status-lovelace:
      mode: yaml
      title: status
      show_in_sidebar: true
      filename: status.yaml
      icon: mdi:lan


#sun
sun:

system_health:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include lights.yaml
switch: !include switch.yaml
scene: !include scene.yaml