#Licht groepen

- platform: group
  name: keuken_group
  entities: 
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3

- platform: group
  name: eetkamer_group
  entities:
    - light.diner_table_1
    - light.diner_table_2
    - light.diner_table_3

- platform: group
  name: woonkamer_group
  entities:
    - light.bloom_tv_light
    - light.livingroom_center_light
    - light.livingroom_standing_lamp

- platform: group
  name: gang_group
  entities:
    - light.hall_1
    - light.hall_2

- platform: group
  name: werkkamer_group
  entities:
    - light.replicator_room_1
    - light.replicator_room_2

- platform: group
  name: slaapkamer_group
  entities:
    - light.bedroom_1
    - light.bedroom_2
    - light.bedroom_3
    - light.wake_up_light_left
    - light.wakeup_light_rechts

- platform: group
  name: badkamer_group
  entities:
    - light.bathroom_1
    - light.bathroom_2
    - light.bathroom_3

- platform: group
  name: Boven_group
  entities:
    - light.badkamer_group
    - light.bathroom_group
    - light.slaapkamer_group
    - light.werkkamer_group
    - light.laundry_room