#switch declarations
- platform: mqtt
  name: "afzuigkap"
  command_topic: "cmnd/afzuiger//POWER"
  state_topic: "cmnd/afzuiger//POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Schuur"
  command_topic: "cmnd/sonoffschuur/POWER"
  state_topic: "cmnd/sonoffschuur/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Wallscreen"
  command_topic: "cmnd/sonoffwallmount/POWER"
  state_topic: "cmnd/sonoffwallmount/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true