views:
  - id: Algemeen nieuw
    icon: mdi:castle
    title: Info Glance
    cards:
    - type: vertical-stack
      cards:
      - type: custom:weather-card
        entity: weather.uden   
      - type: custom:mini-graph-card
        name: Tempratuur
        animate: true
        entities:
          - sensor.living_room_thermostat_temperature
          - sensor.toilet_sensor_temperature
          - sensor.hue_motion_sensor_1_temperature
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          name: Electriciteit verbruik
          entities:
            - sensor.power_consumption
          line_color: yellow
          line_width: 8
          font_size: 75
        - type: custom:mini-graph-card
          name: Luchtvochtigheid
          entities:
            - sensor.living_room_thermostat_humidity
          line_color: blue
          line_width: 8
          font_size: 75
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          name: Gasverbruik
          entities:
            - sensor.hourly_gas_consumption
          line_color: red
          line_width: 8
          font_size: 75
        - type: custom:mini-graph-card
          name: Server CPU
          entities:
            - sensor.cpu_temprature
          line_color: green
          line_width: 8
          font_size: 75
      - type: horizontal-stack
        cards:
        - type: entities
          title: Deur sensoren 
          show_header_toggle: false
          entities:
            - binary_sensor.schuurpoort
            - binary_sensor.schuurdeur
            - binary_sensor.backdoor
            - binary_sensor.frontdoor
    - type: horizontal-stack
      cards:
      - type: light
        name: Woonkamer
        icon: mdi:sofa
        entity: light.woonkamer_group
      - type: light
        name: Eetkamertafel
        icon: mdi:silverware-fork-knife
        entity: light.eetkamer_group
    - type: horizontal-stack
      cards:
      - type: light
        name: keuken
        icon: mdi:fridge-outline
        entity: light.keuken_group
      - type: light
        name: gang
        icon: mdi:hanger
        entity: light.gang_group
    - type: horizontal-stack
      cards:
      - type: light
        name: Replicator
        icon: mdi:printer-3d-nozzle
        entity: light.werkkamer_group
      - type: light
        name: slaapkamer
        icon: mdi:bed-empty
        entity: light.slaapkamer_group 
    # - type: horizontal-stack
    #   cards:
    #   - type: "custom:atomic-calendar"
    #     title: "Kalender"
    #     enableModeChange: true
    #     defaultMode: 1
    #     entities:
    #     - entity: calendar.patrick
    #       type: icon2


  - id: schakelaars
    icon: mdi:light-switch
    title: Schakelaars
    cards:
      - type: horizontal-stack
        cards:
        - type: light
          name: eetkamer lampen
          icon: mdi:silverware-fork-knife
          entity: light.eetkamer_group
        - type: light
          name: keuken lampen
          icon: mdi:fridge-outline
          entity: light.keuken_group
        - type: light
          name: woonkamer
          icon: mdi:sofa
          entity: light.woonkamer_group
      - type: horizontal-stack
        cards:
        - type: light
          name: workspace
          icon: mdi:code-braces
          entity: light.tradfri_driver
        - type: entity-button
          name: Schuur
          icon: mdi:bank
          entity: switch.schuur

resources: !include resources.yaml