views:
  - title: Info Glance
    icon: mdi:castle
    cards:
    #Stack Left
    - type: vertical-stack
      cards:
      - type: custom:weather-card
        entity: weather.uden
      - type: 'custom:neerslag-card'
        title: Neerslag
        entities: 
          - sensor.neerslag_buienalarm_regen_data
          - sensor.neerslag_buienradar_regen_data
      - type: custom:mini-graph-card
        name: Tempratuur
        animate: true
        entities:
          - sensor.living_room_thermostat_temperature
          - sensor.temperature_toilet
          - sensor.bedroom_temperature
          #- sensor.temperature_60 #BathRoom
          #- sensor.temperature_57 #Print Sensor
        line_color: blue
        line_width: 2
        font_size: 100
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          name: Luchtvochtigheid
          entities:
            - sensor.living_room_thermostat_humidity
            - sensor.humidity_61 # bathRoom
            - sensor.humidity_58 # Printer
          line_color: blue
          line_width: 2
          font_size: 100
      - type: horizontal-stack
        cards:
        - type: 'custom:simple-thermostat'
          entity: climate.living_room
          step_layout: row
          name: false
          icon: false
          control: false
          hide:
            temperature: true
            state: true
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: custom:calendar-card
            title: "Agenda Patrick"
            numberOfDays: 3
            progressBar: true
            entities:
              - calendar.patrick
              - calendar.afval_kalender
    #Stack Middle
    - type: vertical-stack
      cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            name: Electriciteit verbruik
            entities:
              - sensor.dsmr_reading_electricity_currently_delivered
            line_color: yellow
            line_width: 2
            font_size: 75
          - type: custom:mini-graph-card
            name: Gasverbruik p/dag
            entities:
              - sensor.dsmr_day_consumption_gas
            line_color: red
            line_width: 2
            font_size: 75
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:          
          - type: custom:mini-graph-card
            name: electriciteit
            entities:
              - sensor.dsmr_day_consumption_electricity_cost_merged
            line_color: yellow
            line_width: 2
            font_size: 75
          - type: custom:mini-graph-card
            name: Gas
            entities:
              - sensor.dsmr_day_consumption_gas_cost
            line_color: red
            line_width: 2
            font_size: 75
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:         
          - type: custom:mini-graph-card
            entities:
              - sensor.paternet_temperature
              #- sensor.glances_tdie_temperature_2
              - sensor.solaredge_temp_sink
            line_color: green
            line_width: 2
            font_size: 100
        - type: horizontal-stack
          cards:
          - type: energy-usage-graph
        - type: horizontal-stack
          cards:
          - type: energy-solar-graph
        - type: horizontal-stack
          cards:
          - type: energy-distribution
        - type: horizontal-stack
          cards:
          - type: entities
            title: Deur sensoren 
            show_header_toggle: false
            entities:
              - binary_sensor.schuur_poort
              - binary_sensor.schuur_deur
              - binary_sensor.back_door
              - binary_sensor.front_door
        - type: horizontal-stack
          cards:
#-------------------------------Schakelaars---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(08, 10, 19)
            name: Schakelaars
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            entity: switch.coffee_maker
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:coffee-maker
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: switch.schuur
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:barn
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: light.workspace
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:soldering-iron
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: input_boolean.sleep_mode
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:sleep
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
        - type: horizontal-stack
          cards:
#-------------------------------Entertainment---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(08, 10, 19)
            name: Entertainment
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:speaker
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - PowerToggle
                device: 46809977
          - type: "custom:button-card"
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - VolumeUp
                device: 46809977
          - type: "custom:button-card"
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - VolumeDown
                device: 46809977
          - type: "custom:button-card"
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:television
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - PowerToggle
                device: 46809976
        - type: horizontal-stack
          cards:
#-------------------------------scenes---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(08, 10, 19)
            name: Scenes
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:weather-sunset
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.ambiance
          - type: "custom:button-card"
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:stove
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.kook_scene
          - type: "custom:button-card"
            entity: input_boolean.study_mode
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:school
            show_name: false        
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: input_boolean.wakeup_enabled
            color_type: card
            color: rgb(08, 10, 19)
            icon: mdi:theme-light-dark
            show_name: false        
            state:
              - value: "on"
                color: rgb(218, 218, 219)
        - type: horizontal-stack
          cards:
#-------------------------------Routine---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(08, 10, 19)
            name: Routine
        - type: horizontal-stack
          cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_datetime.wakeup_time

    #Right Stack
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: light
          name: Woonkamer
          icon: mdi:sofa
          entity: light.woonkamer_lamp
        - type: light
          name: Eetkamertafel
          icon: mdi:silverware-fork-knife
          entity: light.eetkamer_lamp
      - type: horizontal-stack
        cards:
        - type: light
          name: keuken
          icon: mdi:fridge-outline
          entity: light.keuken_lamp
        - type: light
          name: gang
          icon: mdi:hanger
          entity: light.gang_lamp
      - type: horizontal-stack
        cards:
        - type: light
          name: Replicator
          icon: mdi:printer-3d-nozzle
          entity: light.werkkamer_lamp
        - type: light
          name: slaapkamer
          icon: mdi:bed-empty
          entity: light.slaapkamer_lamp
      - type: horizontal-stack
        cards:
        - type: light
          name: badkamer
          icon: mdi:shower
          entity: light.badkamer_lamp
        - type: light
          name: Toilet
          icon: mdi:toilet
          entity: light.toilet
      - type: horizontal-stack
        cards:
        - type: energy-grid-neutrality-gauge
      - type: horizontal-stack
        cards: 
        - type: energy-solar-consumed-gauge
      - type: horizontal-stack
        cards:
        - type: 'custom:vacuum-card'
          entity: vacuum.valetudo_pater_zuiger
          #map: camera.map_data
          stats:
            default:
              - attribute: filter
                unit: uur
                subtitle: Filter
              - attribute: sideBrush
                unit: uur
                subtitle: Zij borstel
              - attribute: mainBrush
                unit: uur
                subtitle: Hoofd borstel
              - attribute: sensor
                unit: uur
                subtitle: Sensors
              - attribute: currentCleanArea
                unit: m2
                subtitle: Oppervlak
              - attribute: currentCleanTime
                unit: min
                subtitle: Zuigtijd
          actions:
          - name: turug naar oplader
            service: vacuum.return_to_base
            icon: 'mdi:home'
          - name: start / pauze
            service: vacuum.start_pause
            icon: 'mdi:play-pause'
