views:
  - id: Algemeen nieuw
    icon: mdi:castle
    title: Info Glance
    cards:
    #Stack Left
    - type: vertical-stack
      cards:
      - type: custom:weather-card
        entity: weather.uden
      - type: custom:mini-graph-card
        name: Tempratuur
        animate: true
        entities:
          - sensor.living_room_thermostat_temperature
          - sensor.temperature_toilet
          - sensor.bedroom_temperature
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: custom:calendar-card
            title: "Agenda Patrick"
            numberOfDays: 7
            progressBar: true
            entities:
              - calendar.patrick
              - calendar.afval_kalender
        - type: horizontal-stack
          cards:
          - type: glance
            title: COVID-19 Nederland
            entities:
              - sensor.netherlands_coronavirus_confirmed
              - sensor.netherlands_coronavirus_current
              - sensor.netherlands_coronavirus_deaths
              - sensor.netherlands_coronavirus_recovered
        - type: horizontal-stack
          cards:
          - type: glance
            title: COVID-19 Wereldwijd
            entities:
              - sensor.worldwide_coronavirus_confirmed
              - sensor.worldwide_coronavirus_current
              - sensor.worldwide_coronavirus_deaths
              - sensor.worldwide_coronavirus_recovered
    #Stack Middle
    - type: vertical-stack
      cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            name: Electriciteit verbruik
            entities:
              - sensor.dsmr_reading_electricity_currently_delivered
            line_color: yellow
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Gasverbruik p/dag
            entities:
              - sensor.dsmr_day_consumption_gas
            line_color: red
            line_width: 8
            font_size: 75
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:          
          - type: custom:mini-graph-card
            name: electriciteit
            entities:
              - sensor.dsmr_day_consumption_electricity_cost_merged
            line_color: yellow
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Gas
            entities:
              - sensor.dsmr_day_consumption_gas_cost
            line_color: red
            line_width: 8
            font_size: 75
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:         
          - type: custom:mini-graph-card
            name: Server CPU
            entities:
              - sensor.cpu_temprature
            line_color: green
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: Luchtvochtigheid
            entities:
              - sensor.living_room_thermostat_humidity
            line_color: blue
            line_width: 8
            font_size: 75
        - type: horizontal-stack
          cards:
          - type: entities
            title: Deur sensoren 
            show_header_toggle: false
            entities:
              - binary_sensor.schuur_poort
              - binary_sensor.schuur_deur
              - binary_sensor.back_door
              - binary_sensor.front_door
        - type: horizontal-stack
          cards:
#-------------------------------Schakelaars---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(67, 73, 82)
            name: Schakelaars
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            entity: switch.coffee_maker
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:coffee-maker
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: switch.schuur
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:barn
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: light.workspace
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:soldering-iron
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
          - type: "custom:button-card"
            entity: input_boolean.sleep_mode
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:sleep
            show_name: false
            state:
              - value: "on"
                color: rgb(218, 218, 219)
        - type: horizontal-stack
          cards:
#-------------------------------Entertainment---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(67, 73, 82)
            name: Entertainment
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:speaker
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - PowerToggle
                device: 46809977
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - VolumeUp
                device: 46809977
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - VolumeDown
                device: 46809977
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:television
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.livingroom_2
                command:
                  - PowerToggle
                device: 46809976
        - type: horizontal-stack
          cards:
#-------------------------------scenes---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(67, 73, 82)
            name: Scenes
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:weather-sunset
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.ambiance
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:stove
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.kook_scene
          - type: "custom:button-card"
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:silverware-variant
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.eten_aan_eettafel
          - type: "custom:button-card"
            entity: input_boolean.wakeup_enabled
            color_type: card
            color: rgb(67, 73, 82)
            icon: mdi:theme-light-dark
            show_name: false        
            state:
              - value: "on"
                color: rgb(218, 218, 219)
        - type: horizontal-stack
          cards:
#-------------------------------Routine---------------------------------------------------
          - type: "custom:button-card" 
            color_type: label-card
            color: rgb(67, 73, 82)
            name: Routine
        - type: horizontal-stack
          cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_datetime.wakeup_time

    #Right Stack
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: light
          name: Woonkamer
          icon: mdi:sofa
          entity: light.woonkamer_group
        - type: light
          name: Eetkamertafel
          icon: mdi:silverware-fork-knife
          entity: light.eetkamer_group
      - type: horizontal-stack
        cards:
        - type: light
          name: keuken
          icon: mdi:fridge-outline
          entity: light.keuken_group
        - type: light
          name: gang
          icon: mdi:hanger
          entity: light.gang_group
      - type: horizontal-stack
        cards:
        - type: light
          name: Replicator
          icon: mdi:printer-3d-nozzle
          entity: light.werkkamer_group
        - type: light
          name: slaapkamer
          icon: mdi:bed-empty
          entity: light.slaapkamer_group
      - type: horizontal-stack
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.living_room
            step_layout: row
            name: false
            icon: false
            control: false
            hide:
              temperature: true
              state: true
      - type: horizontal-stack
        cards:
        - type: custom:xiaomi-vacuum-card
          entity: vacuum.pater_zuiger
          name: Pater-Zuiger
          buttons: true
          labels:
            status: Status
            battery: Batterij
            mode: Modus
            main_brush: Borstel
            side_brush: Zijborstel
            filter: Filter
            sensor: Sensor

  - id: cameras
    title: Surveillance
    icon: mdi:cctv
    panel: true
    cards:
    - type: vertical-stack
      cards:
      - type: custom:surveillance-card
        thumb_interval: 10
        update_interval: 1
        cameras:
          - entity: camera.foscam_voor
          - entity: camera.foscam_achter
          - entity: camera.octoprint



resources: !include resources.yaml